/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f103c6_gpio_driver.h"
#include "stm32f103c6_exti_driver.h"

uint8 IRQ_Flag;


void clockInit(void) {

	RCC_AFIO_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void EXTI_CallBack(void) {
	IRQ_Flag = 1;
}

int main(void) {
	EXTI_config cnf;

	clockInit();

	cnf.EXTI_Map = EXTI9PB9;
	cnf.EXTI_Trigger = EXTI_RISING;
	cnf.P_IRQHandler = EXTI_CallBack;
	cnf.EXTI_EnableState = EXTI_ENABLE;
	MCAL_EXTI_init(&cnf);

	while (1) {
		if (IRQ_Flag) {
			IRQ_Flag = 0;
		} else {  }
	}
}

