/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103c6_usart_driver.h"
#include "stm32f103c6_spi_driver.h"
#include "stm32f103c6_i2c_driver.h"
#include "stm32f103c6_gpio_driver.h"
#include "EEPROM.h"
void clockInit(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

int main(void){
	uint8  ch1[] ={0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	uint8  ch2[7] ={0};
	clockInit();
	EEPROM_init();
	EEPROM_WriteNBytes(0xAF, ch1, 7);
	EEPROM_ReadByte(0xAF, ch2, 7);
	ch1[0]=0xA;
	ch1[1]=0xB;
	ch1[2]=0xC;
	ch1[3]=0xD;
	EEPROM_WriteNBytes(0xFFF, ch1, 4);
	EEPROM_ReadByte(0xFFF, ch2, 4);
	while(1){
	}

}


