/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#define RCC_BASE 	    0x40021000
#define GPIOA_BASE  	0x40010800
#define RCC_CR 	        *(volatile unsigned long *)(0x40021000)


typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long :2;
		volatile unsigned long IOPAEN:1;
	}bits;
}APB2ENR;

typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long SW:2;
		volatile unsigned long :2;
		volatile unsigned long HPRE:4;
		volatile unsigned long PPRE1:3;
		volatile unsigned long PPRE2:3;
		volatile unsigned long :2;
		volatile unsigned long PLLSRC:1;
		volatile unsigned long :1;
		volatile unsigned long PLLMUL:4;

	}bits;
}CFGR;

typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long :20;
		volatile unsigned long MODE13 :2;
		volatile unsigned long CNF13 :2;
	}bits;
}GPIOx_CRH;

typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long :13;
		volatile unsigned long ODR13:1;
	}bits;
}GPIOx_ODR;

volatile CFGR      * RCC_CFGR    = (volatile CFGR      *)(RCC_BASE 	 +0x04);
volatile APB2ENR   * RCC_APB2ENR = (volatile APB2ENR   *)(RCC_BASE 	 +0x18);
volatile GPIOx_CRH * GPIOA_CRH   = (volatile GPIOx_CRH *)(GPIOA_BASE    +0x04);
volatile GPIOx_ODR * GPIOA_ODR   = (volatile GPIOx_ODR *)(GPIOA_BASE    +0x0C);

void clockInit(){

	RCC_CFGR->bits.SW = 0b00;
	RCC_CFGR->bits.HPRE = 0b0000;
	RCC_CFGR->bits.PPRE1 = 0b100;
	RCC_CFGR->bits.PPRE2 = 0b101;
}

int main(void)
{
	int i;
	clockInit();
	RCC_APB2ENR->bits.IOPAEN=0b1;
	GPIOA_CRH->bits.CNF13=0b00;
	GPIOA_CRH->bits.MODE13=0b10;

	for(;;){
		GPIOA_ODR->bits.ODR13=0b1;
		for(i=0;i<5000;i++);
		GPIOA_ODR->bits.ODR13=0b0;
		for( i=0;i<5000;i++);
	}
}
