/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103c6_gpio_driver.h"
#include "LCD.h"
#include "Keypad.h"

#define ZERO 	0x01
#define ONE 	0x79
#define TWO 	0x24
#define THREE 	0x30
#define FOUR 	0x58//0 101 1000
#define FIVE 	0x12
#define SIX 	0x02
#define SEVEN	0x19
#define EIGHT 	0x00
#define NINE 	0x10

void clockInit(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

}

void gpioInit(void){

	GPIO_config cfg;

	cfg.GPIO_PinNumber 		= GPIO_PIN9;
	cfg.GPIO_PinMode   		= GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed	= GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);
	cfg.GPIO_PinNumber 		= GPIO_PIN10;
	cfg.GPIO_PinMode   		= GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed	= GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);
	cfg.GPIO_PinNumber 		= GPIO_PIN11;
	cfg.GPIO_PinMode   		= GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed	= GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);
	cfg.GPIO_PinNumber 		= GPIO_PIN12;
	cfg.GPIO_PinMode   		= GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed	= GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);
	cfg.GPIO_PinNumber 		= GPIO_PIN13;
	cfg.GPIO_PinMode   		= GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed	= GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);
	cfg.GPIO_PinNumber 		= GPIO_PIN14;
	cfg.GPIO_PinMode   		= GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed	= GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);
	cfg.GPIO_PinNumber 		= GPIO_PIN15;
	cfg.GPIO_PinMode   		= GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed	= GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);

	MCAL_GPIO_writePort(GPIOB,((0x7F)<<9));

}

uint8 i = 0,numbers[]={
		ZERO,
		ONE,
		TWO,
		THREE,
		FOUR,
		FIVE,
		SIX,
		SEVEN,
		EIGHT,
		NINE
};
int main(void)
{
	clockInit();
	gpioInit();
	LCD_init();
	KEYPAD_init();

	char data;

	LCD_printString("Hello");
	delay(100);
	LCD_clearScreen();
	LCD_printString("Keypad ready !");
	delay(300);
	LCD_clearScreen();
	while(1){
		MCAL_GPIO_writePort(GPIOB,(numbers[i])<<9);
		delay(80);
		data = KEYPAD_getChar();

		switch(data){
		case '!':
			LCD_clearScreen();
			break;
		case '\0':
			break;
		default:
			LCD_printChar(data);
		}
	if(i==9)i=0;
	else	i++;
	}
}

