/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103c6_gpio_driver.h"
#include "LCD.h"
#include "Keypad.h"
#include "7segment.h"

void clockInit(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

}

int main(void)
{
	clockInit();
	_7segment_init();
	LCD_init();
	KEYPAD_init();

	uint8 i = 0;
	char data;

	LCD_printString("Hello");
	delay(100);
	LCD_clearScreen();
	LCD_printString("Keypad ready !");
	delay(300);
	LCD_clearScreen();
	while(1){

		_7segment_printNumber(i);
		delay(50);

		data = KEYPAD_getChar();
		switch(data){
		case '!':
			LCD_clearScreen();
			break;
		case '\0':
			break;
		default:
			LCD_printChar(data);
		}
		if(i==9)i=0;
		else	i++;
	}
}

