/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#define RCC_BASE 	    0x40021000
#define GPIOA_BASE  	0x40010800
#define AFIO_BASE		0x40010000
#define	EXTI_BASE		0x40010400
#define NVIC_BASE		0xE000E100
typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long AFIOEN:1;
		volatile unsigned long :1;
		volatile unsigned long IOPAEN:1;
		volatile unsigned long IOPBEN:1;
		volatile unsigned long IOPCEN:1;
		volatile unsigned long IOPDEN:1;
		volatile unsigned long IOPEEN:1;
		volatile unsigned long IOPFEN:1;
		volatile unsigned long IOPGEN:1;
	}bits;
}APB2ENR;

typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long EXTI0 :4;
		volatile unsigned long EXTI1 :4;
		volatile unsigned long EXTI2 :4;
		volatile unsigned long EXTI3 :4;
	}bits;
}EXTICR1;

typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long MODE1 :2;
		volatile unsigned long CNF1 :2;
	}bits;
}GPIOx_CRL;

typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long :20;
		volatile unsigned long MODE13 :2;
		volatile unsigned long CNF13 :2;
	}bits;
}GPIOx_CRH;

typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long :13;
		volatile unsigned long ODR13:1;
	}bits;
}GPIOx_ODR;

typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long MR0:1;
		volatile unsigned long MR1:1;
		volatile unsigned long MR2:1;
		volatile unsigned long MR3:1;
		volatile unsigned long MR4:1;
		volatile unsigned long MR5:1;
		volatile unsigned long MR6:1;
		volatile unsigned long MR7:1;
		volatile unsigned long MR8:1;
		volatile unsigned long MR9:1;
		volatile unsigned long MR10:1;
		volatile unsigned long MR11:1;
		volatile unsigned long MR12:1;
		volatile unsigned long MR13:1;
		volatile unsigned long MR14:1;
		volatile unsigned long MR15:1;
		volatile unsigned long MR16:1;
		volatile unsigned long MR17:1;
		volatile unsigned long MR18:1;
		volatile unsigned long MR19:1;
	}bits;
}IMR;
typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long TR0:1;
		volatile unsigned long TR1:1;
		volatile unsigned long TR2:1;
		volatile unsigned long TR3:1;
		volatile unsigned long TR4:1;
		volatile unsigned long TR5:1;
		volatile unsigned long TR6:1;
		volatile unsigned long TR7:1;
		volatile unsigned long TR8:1;
		volatile unsigned long TR9:1;
		volatile unsigned long TR10:1;
		volatile unsigned long TR11:1;
		volatile unsigned long TR12:1;
		volatile unsigned long TR13:1;
		volatile unsigned long TR14:1;
		volatile unsigned long TR15:1;
		volatile unsigned long TR16:1;
		volatile unsigned long TR17:1;
		volatile unsigned long TR18:1;
		volatile unsigned long TR19:1;
	}bits;
}RTSR;
typedef union{
	volatile unsigned long ALL_FIELDS;
	struct {
		volatile unsigned long PR0:1;
		volatile unsigned long PR1:1;
		volatile unsigned long PR2:1;
		volatile unsigned long PR3:1;
		volatile unsigned long PR4:1;
		volatile unsigned long PR5:1;
		volatile unsigned long PR6:1;
		volatile unsigned long PR7:1;
		volatile unsigned long PR8:1;
		volatile unsigned long PR9:1;
		volatile unsigned long PR10:1;
		volatile unsigned long PR11:1;
		volatile unsigned long PR12:1;
		volatile unsigned long PR13:1;
		volatile unsigned long PR14:1;
		volatile unsigned long PR15:1;
		volatile unsigned long PR16:1;
		volatile unsigned long PR17:1;
		volatile unsigned long PR18:1;
		volatile unsigned long PR19:1;
	}bits;
}PR;

#define NVIC_ISER0 *(volatile unsigned long *)(NVIC_BASE)
volatile APB2ENR   * RCC_APB2ENR    = (volatile APB2ENR   *)(RCC_BASE 	+0x18);
volatile EXTICR1   * AFIO_EXTICR1   = (volatile EXTICR1   *)(AFIO_BASE	+0x08);
volatile IMR       * EXTI_IMR       = (volatile IMR       *)(EXTI_BASE	+0x00);
volatile RTSR      * EXTI_RTSR      = (volatile RTSR      *)(EXTI_BASE	+0x08);
volatile PR	       * EXTI_PR        = (volatile PR	      *)(EXTI_BASE	+0x14);
volatile GPIOx_CRL * GPIOA_CRL      = (volatile GPIOx_CRL *)(GPIOA_BASE	+0x00);
volatile GPIOx_CRH * GPIOA_CRH      = (volatile GPIOx_CRH *)(GPIOA_BASE +0x04);
volatile GPIOx_ODR * GPIOA_ODR      = (volatile GPIOx_ODR *)(GPIOA_BASE +0x0C);


void clockInit(void){

	RCC_APB2ENR->bits.IOPAEN = 0b1;
	RCC_APB2ENR->bits.AFIOEN = 0b1;
}
void gpioInit(void){

	GPIOA_CRL->bits.CNF1 = 0b01;
	GPIOA_CRL->bits.MODE1 = 0b00;

	GPIOA_CRH->bits.CNF13 = 0b00;
	GPIOA_CRH->bits.MODE13 = 0b10;
}

int main(void)
{
	clockInit();
	gpioInit();
	AFIO_EXTICR1->bits.EXTI0 = 0b0000;
	EXTI_IMR->bits.MR0 = 0b1;
	EXTI_RTSR->bits.TR0 = 0b1;
	NVIC_ISER0|=(1<<6);
	while(1);
}

void EXTI0_IRQHandler(void){

	GPIOA_ODR->bits.ODR13^=0b1;

	EXTI_PR->bits.PR0=0b1;
}
