/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "Platform_Types.h"

#define RCC_BASE 	    0x40021000
#define GPIOPA_BASE  	0x40010800

#define RCC_APB2ENR	  *(volatile uint32 *) (RCC_BASE     +0x18)
#define RCC_APB2ENR_IOPAEN 2
#define set(reg,bit) reg|=1<<bit

typedef union{
	uint32 ALL_FIELDS;
	struct {
		uint32 :13;
		uint32 pin13:1;
	}pins;
}GPIOPA_ODR;

typedef union{
	uint32 ALL_FIELDS;
	struct {
		uint32 :20;
		uint32 modepin13 :4;
	}modes;
}GPIOPA_CRH;

volatile GPIOPA_CRH * CRH= (volatile GPIOPA_CRH *)(GPIOPA_BASE   +0x04);
volatile GPIOPA_ODR * ODR= (volatile GPIOPA_ODR *)(GPIOPA_BASE   +0x0C);
int main(void)
{

	set(RCC_APB2ENR,RCC_APB2ENR_IOPAEN);

	CRH->modes.modepin13=2;

	for(;;){
		ODR->pins.pin13=1;
		for(int i=0;i<5000;i++);
		ODR->pins.pin13=0;
		for(int i=0;i<5000;i++);
	}
}
