/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103c8_gpio_driver.h"


void clockInit(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void gpioInit(void){

	GPIO_config cfg;
	cfg.GPIO_PinNumber = GPIO_PIN1;
	cfg.GPIO_PinMode   = GPIO_MODE_INPUT_FLO;
	cfg.GPIO_OutputSpeed = GPIO_INPUT;
	MCAL_GPIO_init(GPIOA, &cfg);
	cfg.GPIO_PinNumber   = GPIO_PIN1;
	cfg.GPIO_PinMode     = GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed = GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);

	cfg.GPIO_PinNumber   = GPIO_PIN13;
	cfg.GPIO_PinMode     = GPIO_MODE_INPUT_FLO;
	cfg.GPIO_OutputSpeed = GPIO_INPUT;
	MCAL_GPIO_init(GPIOA, &cfg);

	cfg.GPIO_PinNumber = GPIO_PIN13;
	cfg.GPIO_PinMode   = GPIO_MODE_OUTPUT_PP;
	cfg.GPIO_OutputSpeed = GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOB, &cfg);

	MCAL_GPIO_writePin(GPIOB, GPIO_PIN1, GPIO_HIGH);
	MCAL_GPIO_writePin(GPIOB, GPIO_PIN13, GPIO_HIGH);

}
void delay(int d){

	unsigned long i,j;
	for(i=0;i<d;i++)
		for(j=0;j<255;j++);
}

int main(void)
{
	clockInit();
	gpioInit();

	while(1){

		if(MCAL_GPIO_readPin(GPIOA, GPIO_PIN1)== GPIO_LOW){

			MCAL_GPIO_togglePin(GPIOB, GPIO_PIN1);
			while(MCAL_GPIO_readPin(GPIOA, GPIO_PIN1)== GPIO_LOW);
		}
		if(MCAL_GPIO_readPin(GPIOA, GPIO_PIN13)== GPIO_HIGH){

			MCAL_GPIO_togglePin(GPIOB, GPIO_PIN13);
			delay(1);
		}
	}
}

